name: Checkout Actions
on: [push]
jobs:
  checkout-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before Checkout
        run: ls -a
      - name: Checkout Actions
        uses: actions/checkout@v3
      - name: List Files After Checkout
        run: ls -a
