#yaml code for printing a string once Working dir and shell workflow is completed
name: Dependent Workflow
on:
  [push]
  # workflow_run:
  #   workflows: ["Working dir and shell"]
  #   types: [completed]
jobs:
  echo-string:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a dependent workflow that runs after 'Working dir and shell' completes."
